env:
  global:
    - CC_TEST_REPORTER_ID=ebf2dc804de2496f28003fba4daf2669c0796389802bf8868b0a00baecef6d29
language: node_js
node_js:
  - "stable"
services:
  - postgresql
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm install
  - npm run test --maxWorkers=4

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: npm run coverage