language: node_js
node_js:
  - "stable"
install: npm install
services:
  - postgresql
before_script:
  - psql -c 'create database quickdecks_test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
  - npx knex migrate:down --env=test
  - npx knex migrate:latest --env=test
script: npm test
after_success: npm run coverage
